### ISSUE TITLE
Run the ANFHealthCheck on local computer

### ISSUE THREAD

**Issue by alishavez7** [seanluce/ANFHealthCheck#2]
Hi Sean,

I am trying to test the ANFHealthCheck runbook on my local computer first before try it through azure automation but when i run it nothing happened.

I am using the below parameter to run it locally.

.\ANFHealthCheck.ps1 -SubID xxxxxx -OutFile myfile.html

I only see the below msg and nothing happened, its been running for long time without any progress or error.

"Unable to Connect-AzAccount using these parameters" and after this msg it select the subscription and then nothing happened.

**Comment by seanluce** [comment]
Must run Connect-AzAccount first when running locally.
