### ISSUE TITLE
Incorrect variable used for Dry Run control

### ISSUE THREAD

**Issue by jngibert** [seanluce/ANFHealthCheck#5]
On line 280 in ANFHealthCheck.ps1 the wrong variable is used.

The line currently reads:
`if($enableVolumeCapacityRemediationDryRun -eq $false) {`

it needs to be changed to:
`if($enablePoolCapacityRemediationDryRun -eq $false) {`

**Comment by seanluce** [comment]
Thank you, @jngibert. This has been resolved.
