### ISSUE TITLE
Remediation mode: Source capacity pool resize is done ahead of volume resize

### ISSUE THREAD

**Issue by snigdhamovva** [seanluce/ANFHealthCheck#6]
In scenario of using health check remediation mode for shrinking - the capacity pools are resized first and then volumes which is a problem as capacity pool will not shrink after volume size is reduced

**Comment by seanluce** [comment]
Thank you, Snigdha. I did have some time to investigate this issue and unfortunately there is not a good fix at this time. My recommendation is to run the script twice with a few hours in between each run. The first run will shrink the volumes. The second run will be able to see the new volume sizes and use those metrics to size the pools accordingly.
